### PR TITLE
Added custom test-cases; Parsing with bs4 (problemsets); Fixes

### PR DESCRIPTION
**Pull request by npanuhin**
Now it checks if each file in the _input_ directory matches the file in the _output_ directory.
Thus, the user can create a file with a custom name (the same name should exist in _input_ and _output_ folders).

Also all instances of `in` are replaced by `out`. But this can be bad, for example, for such names: w**in**dow, co**in**, beg**in**

@RohitMazumder

### CODE REVIEW

**Comment by npanuhin** [comment]
Now there is no problem with file names: The same name in _input_ and _output_ folders: `test` and `user_test`

**Comment by npanuhin** [comment]
Now all commands run in separate threads, which prevents Sublime Text from freezing (for example, when compiling a program)

**Comment by npanuhin** [comment]
Now it prints the result immediately after each execution - I think it is much better.

**Comment by npanuhin** [comment]
Finally, I changed the parsing system to the `bs4` library and implemented problemset parsing.
However, there are other things that need to be changed. For example, parsing a set of problems takes about 3-4 seconds, and during this time the user is not shown anything.

@RohitMazumder

**Comment by npanuhin** [comment]
@RohitMazumder, excuse me, what about these changes?

**Comment by RohitMazumder** [comment]
@npanuhin Sorry for the long delay in replying. 
I have a concern regarding this transition to bs4. So, a user needs to have bs4 installed in his/her system before using this, right?

**Comment by npanuhin** [comment]
@RohitMazumder, no, the `bs4` library [was implemented](https://github.com/wbond/package_control_channel/blob/7487b83bc3de0c9bfeda82caba12fc6d4c58816b/repository/dependencies.json#L91) specifically for Package Control, and if you open `dependencies.json` file it will be there:
```json
{
	"*": {
		"*": [
			"bs4"
		]
	}
}
```
So Package Control automatically installs the custom `bs4` library from [jlegewie/sublime-beautifulsoup4](https://github.com/jlegewie/sublime-beautifulsoup4), when parsing `dependencies.json`.
More about dependencies [here](https://packagecontrol.io/docs/dependencies).

**Comment by RohitMazumder** [comment]
That's great! I'll review the changes and merge this by tomorrow :)

**Comment by npanuhin** [comment]
Ok, thank you very much!

**Review by RohitMazumder — APPROVED** [review]
Good work!

**Comment by npanuhin** [comment]
Thank you!

**Pull request merged**
